<a href="https://colab.research.google.com/github/codewithtrisha09/ML-LAB/blob/main/WEEK_01NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAME: TRISHA SHETTY
REG NO:240962606
AIML-A 2


##LAB 1 NUMPY##

Q1 Convert a 1-D array into a 2-D array with 3 rows.

In [ ]:
import numpy as np
Assign_1=np.array([0,1,2,3,4,5,6,7,8])
result = Assign_1.reshape(3, 3)
print(result)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q2 Replace all odd numbers in the given array with -1

In [ ]:
import numpy as np
Assign_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Assign_2[Assign_2 % 2 == 1] = -1
print(Assign_2)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q3 Find the positions of:
elements in x where its value is more than its corresponding element in y, and elements in x where its value is
equals to its corresponding element in y.

In [ ]:
import numpy as np

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
greater = np.where(x > y)
equal = np.where(x == y)

print(greater)
print(equal)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


Q4 Extract the first four columns of this 2-D array.

In [ ]:
import numpy as np
Assign_4 = np.arange(100).reshape(5, -1)
result = Assign_4[:, :4]
print(result)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [ ]:
Additional Questions

Q1 Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [ ]:
import numpy as np
random_array = np.random.randint(30, 41, size=10)
print(random_array)


[31 37 33 33 32 32 30 40 39 32]


Q2. Consider the following matrices :
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
Write a python program to perform the following using Numeric Python (numpy).
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
iii) Product of two matrices A and B, and print the resultant matrix D
iv) Sort the elements of resultant matrix C and print the resultant Matrix E.
v) Transpose the Matrix E and print the result

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

B = np.array([[7, 8, 10],
              [4, 5, 6],
              [1, 2, 3]])

C = A + B
E_sub = A - B
print("Matrix C (Addition):\n", C)
print("Matrix E (Subtraction):\n", E_sub)


Matrix C (Addition):
 [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
Matrix E (Subtraction):
 [[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [ ]:
print("\n ii) Matrix Sums ")
sum_A = np.sum(A)
sum_col_B = np.sum(B, axis=0)
sum_row_C = np.sum(C, axis=1)
print("Sum of all elements of Matrix A:", sum_A)
print("Sum of each column of Matrix B:", sum_col_B)
print("Sum of each row of Matrix C:", sum_row_C)



 ii) Matrix Sums 
Sum of all elements of Matrix A: 46
Sum of each column of Matrix B: [12 15 19]
Sum of each row of Matrix C: [31 30 31]


In [ ]:
print("\n(iii) Matrix Multiplication")
D = np.dot(A, B)
print("Matrix D (Product of A and B):\n", D)



(iii) Matrix Multiplication
Matrix D (Product of A and B):
 [[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


In [ ]:
print("\n (iv)Sorting")
E=np.sort(C,axis=None).reshape(C.shape)
print(" Matrix E (Sorted elements of C):\n",E)


 (iv)Sorting
 Matrix E (Sorted elements of C):
 [[ 8  8  8]
 [10 10 10]
 [12 13 13]]


In [ ]:
print("\n (v) Transpose of Matrix E")
E_transposed=E.T
print(" Transpose of E:\n",E_transposed)


 (v) Transpose of Matrix E
 Transpose of E:
 [[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
